//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace pjsua2xamarin.pjsua2 {

public enum pjmedia_jb_discard_algo {
  PJMEDIA_JB_DISCARD_NONE = 0,
  PJMEDIA_JB_DISCARD_STATIC,
  PJMEDIA_JB_DISCARD_PROGRESSIVE
}

}
